### PR TITLE
Change price to $100

### PR DESCRIPTION
**Pull request by runfequinor**
$200 is too steep of a price, so lowering to $100 will earn us more.

Discussed with Mama and she agrees.

### CODE REVIEW

**Comment by TommyChan6** [comment]
remove the 1 in line 28 plz xD

**Comment by olvemaudal** [comment]
Thanks for you nice suggestion. I will discuss it further with Mama and my brother.

But can you please fix the accidentaly 1 character in your first commit.

**Comment by nicolayro** [comment]
No! The price should increase due to inflation! Like this: #314

**Comment by olvemaudal** [comment]
Lets give it a try! Great suggestion. Great work. Nice changes.

**Pull request merged**
